greeting:
  # `message` is the response given by the greeting endpoint.
  message: "${GREETING_MESSAGE}"

  # `extra` contains an optional message to include with greetings.
  extra: "${GREETING_EXTRA}"
